Repository opennars/opennars, pull requests merged in 2018-06, with the labels that each got.

#317 New: Multi-Threading: Support to run the reasoner with multiple threa…
  src/main/java/org/opennars/control/GeneralInferenceControl.java
  src/main/java/org/opennars/control/TemporalInferenceControl.java
  src/main/java/org/opennars/control/concept/ProcessGoal.java
  src/main/java/org/opennars/control/concept/ProcessJudgment.java
  src/main/java/org/opennars/control/concept/ProcessQuestion.java
  src/main/java/org/opennars/control/concept/ProcessTask.java
  src/main/java/org/opennars/entity/Concept.java
  src/main/java/org/opennars/inference/RuleTables.java
  src/main/java/org/opennars/main/Nar.java
  src/main/java/org/opennars/storage/Memory.java
Labels: enhancement, performance

#322 moved members
  src/main/java/org/opennars/entity/Task.java
Labels: refactor

#320 removed unnecessary specialization
  src/main/java/org/opennars/inference/UtilityFunctions.java
Labels: refactor

#321 Task make
  src/main/java/org/opennars/control/DerivationContext.java
  src/main/java/org/opennars/control/TemporalInferenceControl.java
  src/main/java/org/opennars/control/concept/ProcessAnticipation.java
  src/main/java/org/opennars/entity/Task.java
  src/main/java/org/opennars/inference/CompositionalRules.java
  src/main/java/org/opennars/io/Narsese.java
  src/main/java/org/opennars/main/Nar.java
  src/main/java/org/opennars/operator/FunctionOperator.java
  src/main/java/org/opennars/operator/mental/Anticipate.java
  src/main/java/org/opennars/operator/mental/Believe.java
  src/main/java/org/opennars/operator/mental/Evaluate.java
  src/main/java/org/opennars/operator/mental/Feel.java
  src/main/java/org/opennars/operator/mental/Name.java
  src/main/java/org/opennars/operator/mental/Want.java
  src/main/java/org/opennars/operator/mental/Wonder.java
  src/main/java/org/opennars/plugin/mental/Abbreviation.java
  src/main/java/org/opennars/plugin/mental/Counting.java
  src/main/java/org/opennars/plugin/mental/Emotions.java
  src/main/java/org/opennars/plugin/mental/InternalExperience.java
  src/main/java/org/opennars/plugin/perception/VisionChannel.java
  src/main/java/org/opennars/storage/Memory.java
  src/test/java/org/opennars/core/ReplaceIntervalTest.java
Labels: refactor

#324 Task make (2)
  src/main/java/org/opennars/control/DerivationContext.java
  src/main/java/org/opennars/control/concept/ProcessAnticipation.java
  src/main/java/org/opennars/control/concept/ProcessGoal.java
  src/main/java/org/opennars/entity/Task.java
  src/main/java/org/opennars/entity/package-info.java
  src/main/java/org/opennars/inference/CompositionalRules.java
  src/main/java/org/opennars/io/Narsese.java
  src/main/java/org/opennars/main/Nar.java
  src/main/java/org/opennars/operator/FunctionOperator.java
  src/main/java/org/opennars/operator/mental/Anticipate.java
  src/main/java/org/opennars/operator/mental/Believe.java
  src/main/java/org/opennars/operator/mental/Evaluate.java
  src/main/java/org/opennars/operator/mental/Feel.java
  src/main/java/org/opennars/operator/mental/Name.java
  src/main/java/org/opennars/operator/mental/Want.java
  src/main/java/org/opennars/operator/mental/Wonder.java
  src/main/java/org/opennars/plugin/mental/Abbreviation.java
  src/main/java/org/opennars/plugin/mental/Counting.java
  src/main/java/org/opennars/plugin/mental/Emotions.java
  src/main/java/org/opennars/plugin/mental/InternalExperience.java
  src/main/java/org/opennars/plugin/perception/VisionChannel.java
  src/main/java/org/opennars/storage/Memory.java
Labels: refactor

#323 Long Term Stability Test (1)
  src/test/java/org/opennars/core/LongTermStability.java
Labels: testing

#331 Long Term Stability Test (2)
  src/test/java/org/opennars/core/LongTermStability.java
Labels: testing

#339 Configurable Nar ctor
  src/main/config/defaultConfig.xml
  src/main/java/org/opennars/io/ConfigReader.java
  src/main/java/org/opennars/main/Nar.java
  src/main/java/org/opennars/main/Shell.java
  src/test/java/org/opennars/core/ApplySubstituteTest.java
  src/test/java/org/opennars/core/AttentionTest.java
  src/test/java/org/opennars/core/LongTermStability.java
  src/test/java/org/opennars/core/NALTest.java
  src/test/java/org/opennars/core/ReplaceIntervalTest.java
  src/test/java/org/opennars/core/StabilityTest.java
  src/test/java/org/opennars/core/TermTest.java
  src/test/java/org/opennars/core/VariableTest.java
  src/test/java/org/opennars/core/bag/BagOperationsTest.java
  src/test/java/org/opennars/perf/BagPerf.java
  src/test/java/org/opennars/perf/NALPerfLoop.java
  src/test/java/org/opennars/perf/NALStressMeasure.java
  src/test/java/org/opennars/util/test/TuneTuffy.java
Labels: refactor

#346 Anticipate
  src/main/java/org/opennars/operator/mental/Anticipate.java
Labels: documentation

#347 Anticipate: rename + code motion
  src/main/java/org/opennars/operator/mental/Anticipate.java
Labels: refactor

#348 Anticipate: removed commented code
  src/main/java/org/opennars/operator/mental/Anticipate.java
Labels: refactor

#349 removed wrong documentation
  src/main/java/org/opennars/control/concept/ProcessGoal.java
  src/main/java/org/opennars/entity/BudgetValue.java
  src/main/java/org/opennars/entity/Concept.java
  src/main/java/org/opennars/entity/Item.java
  src/main/java/org/opennars/entity/Sentence.java
  src/main/java/org/opennars/entity/Stamp.java
  src/main/java/org/opennars/entity/TermLink.java
  src/main/java/org/opennars/inference/CompositionalRules.java
  src/main/java/org/opennars/inference/LocalRules.java
  src/main/java/org/opennars/inference/RuleTables.java
  src/main/java/org/opennars/inference/StructuralRules.java
  src/main/java/org/opennars/io/Narsese.java
  src/main/java/org/opennars/io/Symbols.java
  src/main/java/org/opennars/io/events/TextOutputHandler.java
  src/main/java/org/opennars/language/CompoundTerm.java
  src/main/java/org/opennars/language/Conjunction.java
  src/main/java/org/opennars/language/DifferenceExt.java
  src/main/java/org/opennars/language/DifferenceInt.java
  src/main/java/org/opennars/language/Disjunction.java
  src/main/java/org/opennars/language/Equivalence.java
  src/main/java/org/opennars/language/ImageExt.java
  src/main/java/org/opennars/language/ImageInt.java
  src/main/java/org/opennars/language/Implication.java
  src/main/java/org/opennars/language/Inheritance.java
  src/main/java/org/opennars/language/Instance.java
  src/main/java/org/opennars/language/InstanceProperty.java
  src/main/java/org/opennars/language/IntersectionExt.java
  src/main/java/org/opennars/language/IntersectionInt.java
  src/main/java/org/opennars/language/Negation.java
  src/main/java/org/opennars/language/Product.java
  src/main/java/org/opennars/language/Property.java
  src/main/java/org/opennars/language/SetExt.java
  src/main/java/org/opennars/language/SetInt.java
  src/main/java/org/opennars/language/SetTensional.java
  src/main/java/org/opennars/language/Similarity.java
  src/main/java/org/opennars/language/Statement.java
  src/main/java/org/opennars/main/Nar.java
  src/main/java/org/opennars/operator/Operation.java
  src/main/java/org/opennars/operator/Operator.java
  src/main/java/org/opennars/plugin/mental/FullInternalExperience.java
  src/main/java/org/opennars/plugin/mental/InternalExperience.java
  src/main/java/org/opennars/storage/Memory.java
  src/test/java/org/opennars/core/SaveLoadMemoryTest.java
Labels: documentation
