Repository opennars/opennars, pull requests merged in 2018-05, with the labels that each got.

#177 Refactoring ConceptProcessing
  src/main/java/org/opennars/control/ConceptProcessing.java
Labels: refactor

#200 docs(repo): contributing file now mentioned updating changelog
  CONTRIBUTING.md
Labels: documentation

#211 Refactor: renamed NAR to Nar (2)
  src/main/java/org/opennars/entity/Sentence.java
  src/main/java/org/opennars/io/Narsese.java
  src/main/java/org/opennars/io/events/AnswerHandler.java
  src/main/java/org/opennars/io/events/EventHandler.java
  src/main/java/org/opennars/io/events/Events.java
  src/main/java/org/opennars/io/events/OutputHandler.java
  src/main/java/org/opennars/io/events/TextOutputHandler.java
  src/main/java/org/opennars/main/Nar.java
  src/main/java/org/opennars/main/Operators.java
  src/main/java/org/opennars/main/Parameters.java
  src/main/java/org/opennars/main/Plugins.java
  src/main/java/org/opennars/main/Shell.java
  src/main/java/org/opennars/operator/FunctionOperator.java
  src/main/java/org/opennars/operator/Operator.java
  src/main/java/org/opennars/operator/mental/Anticipate.java
  src/main/java/org/opennars/plugin/Plugin.java
  src/main/java/org/opennars/plugin/mental/Abbreviation.java
  src/main/java/org/opennars/plugin/mental/ComplexEmotions.java
  src/main/java/org/opennars/plugin/mental/Counting.java
  src/main/java/org/opennars/plugin/mental/Emotions.java
  src/main/java/org/opennars/plugin/mental/InternalExperience.java
  src/main/java/org/opennars/plugin/misc/RuntimeNARSettings.java
  src/main/java/org/opennars/plugin/perception/SensoryChannel.java
  src/main/java/org/opennars/plugin/perception/VisionChannel.java
  src/main/java/org/opennars/plugin/perception/VisualSpace.java
  src/main/java/org/opennars/storage/Memory.java
  src/test/java/org/opennars/core/ApplySubstituteTest.java
  src/test/java/org/opennars/core/AttentionTest.java
  src/test/java/org/opennars/core/NALTest.java
  src/test/java/org/opennars/core/TermTest.java
  src/test/java/org/opennars/core/VariableTest.java
  src/test/java/org/opennars/core/bag/BagOperationsTest.java
  src/test/java/org/opennars/perf/BagPerf.java
  src/test/java/org/opennars/perf/NALPerfLoop.java
  src/test/java/org/opennars/perf/NALStressMeasure.java
  src/test/java/org/opennars/util/io/ExampleFileInput.java
  src/test/java/org/opennars/util/test/ConceptMonitor.java
  src/test/java/org/opennars/util/test/OutputCondition.java
  src/test/java/org/opennars/util/test/OutputContainsCondition.java
  src/test/java/org/opennars/util/test/OutputEmptyCondition.java
  src/test/java/org/opennars/util/test/OutputNotContainsCondition.java
  src/test/java/org/opennars/util/test/TuneTuffy.java
Labels: refactor

#224 Refactor: cleanup
  src/main/java/org/opennars/entity/TruthValue.java
  src/main/java/org/opennars/storage/LevelBag.java
Labels: refactor

#219 Interface for Nar
  src/main/java/org/opennars/interfaces/Eventable.java
  src/main/java/org/opennars/interfaces/InputFileConsumer.java
  src/main/java/org/opennars/interfaces/Multistepable.java
  src/main/java/org/opennars/interfaces/NarseseConsumer.java
  src/main/java/org/opennars/interfaces/Pluggable.java
  src/main/java/org/opennars/interfaces/Resetable.java
  src/main/java/org/opennars/interfaces/SensoryChannelConsumer.java
  src/main/java/org/opennars/interfaces/TaskConsumer.java
  src/main/java/org/opennars/interfaces/pub/Reasoner.java
  src/main/java/org/opennars/main/Nar.java
Labels: refactor

#229 Refactor ConceptProcessing.executeDecision()
  src/main/java/org/opennars/control/ConceptProcessing.java
Labels: refactor

#222 Refactoring of TemporalRules.temporalInduction()
  src/main/java/org/opennars/inference/TemporalRules.java
Labels: refactor

#212 Refactoring of StructuralRules.groupSequence()
  src/main/java/org/opennars/inference/StructuralRules.java
Labels: refactor

#228 Refactoring of TemporalRules.RuleTables (1)
  src/main/java/org/opennars/inference/RuleTables.java
Labels: refactor

#231 Refactor reason() into multiple methods (2)
  src/main/java/org/opennars/inference/RuleTables.java
Labels: refactor

#232 Variables.findSubstitute()
  src/main/java/org/opennars/language/Variables.java
Labels: refactor

#233 ConceptProcessing.processJudgment()
  src/main/java/org/opennars/control/ConceptProcessing.java
Labels: refactor

#230 Refactor: CompositionalRules.introVarOuter()
  src/main/java/org/opennars/inference/CompositionalRules.java
Labels: refactor

#242 SyllogisticRules.conditionalDedInd()
  src/main/java/org/opennars/inference/RuleTables.java
  src/main/java/org/opennars/inference/SyllogisticRules.java
  src/main/java/org/opennars/language/Statement.java
Labels: refactor

#259 CompositionalRules.decomposeCompound()
  src/main/java/org/opennars/inference/CompositionalRules.java
  src/main/java/org/opennars/inference/TruthFunctions.java
Labels: refactor

#256 Documentation of NAL
  src/main/java/org/opennars/inference/BudgetFunctions.java
  src/main/java/org/opennars/inference/CompositionalRules.java
  src/main/java/org/opennars/inference/StructuralRules.java
  src/main/java/org/opennars/inference/SyllogisticRules.java
Labels: documentation

#257 Resettable Memory
  src/main/java/org/opennars/interfaces/Resettable.java
  src/main/java/org/opennars/interfaces/pub/Reasoner.java
  src/main/java/org/opennars/storage/Memory.java
Labels: refactor

#265 Terms.reduceComponents() family
  src/main/java/org/opennars/language/Terms.java
Labels: documentation

#258 CompositionalRules.decomposeStatement()
  src/main/java/org/opennars/inference/CompositionalRules.java
Labels: refactor

#268 Terms.equalSubjectPredicateInRespectToImageAndProduct()
  src/main/java/org/opennars/language/Terms.java
Labels: refactor

#269 added nal7.decomposeCompound
  src/test/resources/nal/single_step/nal7.decomposeCompound.nal
Labels: testing

#278 better Sentence documentation
  src/main/java/org/opennars/entity/Sentence.java
Labels: documentation

#280 SyllogisticRules.conditionalAbd()
  src/main/java/org/opennars/inference/SyllogisticRules.java
Labels: refactor

#266 Terms: renamed parameters and fixed docs
  src/main/java/org/opennars/language/Terms.java
Labels: documentation, refactor

#293 LevelBag: levelIndex Overflow
  src/main/java/org/opennars/storage/LevelBag.java
Labels: bug

#297 StructuralRules.groupSequence(): Rewrite
  src/main/java/org/opennars/inference/StructuralRules.java
Labels: bug, refactor

#300 Docs: README.md: kicked history and sourcecode status out for now, links
  README.md
Labels: documentation

#299 Docs: README.md
  README.md
Labels: documentation

#295 Fix: locking for concept and new tasks
  src/main/java/org/opennars/control/GeneralInferenceControl.java
  src/main/java/org/opennars/storage/Memory.java
Labels: bug, enhancement

#306 Docs: StructuralRules.transformProductImage()
  src/main/java/org/opennars/inference/StructuralRules.java
Labels: documentation

#309 removed NotImplemented dependency
  src/main/java/org/opennars/language/Variable.java
Labels: refactor

#315 RuleTables.asymmetricAsymmetric(): removed unnecessary switch
  src/main/java/org/opennars/inference/RuleTables.java
Labels: refactor

#314 Split Stability Test
  src/test/java/org/opennars/core/StabilityTest.java
  src/test/java/org/opennars/util/io/ExampleFileInput.java
  src/test/resources/nal/multi_step/long_term_stability.nal
  src/test/resources/nal/stability/long_term_stability.nal
Labels: refactor, testing
